//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PProjectK.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportEquipment
    {
        public int IDSportEquipment { get; set; }
        public string NameEuipment { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> IDCo { get; set; }
        public Nullable<int> IDSport { get; set; }
        public Nullable<int> IDZd { get; set; }
    
        public virtual Bild Bild { get; set; }
        public virtual CounditionEquipment CounditionEquipment { get; set; }
        public virtual VidSport VidSport { get; set; }
    }
}
